version: '3.8'

services:
  app:
    container_name: shop-app
    build:
      context: .
      dockerfile: Dockerfile.combined
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - sqlite_data:/app/data
    ports:
      - "80:80"
    environment:
      - DEBUG=0
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=sqlite:///data/db.sqlite3
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  sqlite_data: 