FROM node:18-alpine

# Установка рабочей директории
WORKDIR /app

# Установка дополнительных зависимостей
RUN apk add --no-cache python3 make g++

# Копирование package.json и package-lock.json
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Копирование исходного кода
COPY . .

# Открытие порта для разработки
EXPOSE 3000

# Запуск приложения в режиме разработки
CMD ["npm", "start"] 